### ISSUE TITLE
Hueys don't have CTLD menu

### ISSUE THREAD

**Issue by Overcaffed** [delenda-delenda/bti-issues#3]
Tried all three but the menu was nowhere to be seen!

**Comment by delenda-delenda** [comment]
Heli pilots weren't renamed to the accepted names in the list - this has been done.
Also added the CTLD Pickup zone to the list of pickup zones.

CTLD menu now appearing after a quick test.

**Comment by Overcaffed** [comment]
CTLD menu showing up \o/
